import React, { useState } from "react";
import { HomeNavbar } from "./HomeView";
import { MinimalFooter } from "./home/MinimalFooter";
import { ThemeProvider } from "./home/ThemeContext";
import { AuroraBackground } from "../motion/AuroraBackground";
import { ChevronDown, ArrowRight, ArrowLeft } from "lucide-react";

interface FaqViewProps {
  onSignIn: () => void;
  onSignUp: () => void;
  isLoggedIn?: boolean;
  onGoToDashboard?: () => void;
  onLogout?: () => void;
  userEmail?: string;
  onGoHome: () => void;
  onNavigate: (path: string) => void;
}

const FAQS = [
  {
    id: "q1",
    question: "What is RateCap?",
    answer: "RateCap is a readiness and safety platform designed to help engineering teams run controlled, authorized performance assessments. It converts observed application behavior into evidence-backed reports that can be shared and defended responsibly."
  },
  {
    id: "q2",
    question: "Who is RateCap designed for?",
    answer: "RateCap is built for engineering teams, QA professionals, and stakeholders who need to validate application capacity and reliability. It provides a structured, defensive approach to load testing without requiring deep performance engineering expertise."
  },
  {
    id: "q3",
    question: "What does a RateCap readiness score mean?",
    answer: "The readiness score (0-100) is a deterministic metric based on observed reliability, latency, capacity behavior, stability, and hygiene during a test run. It is not an unconditional guarantee of performance, but rather an empirical measurement of behavior under a specifically declared test envelope."
  },
  {
    id: "q4",
    question: "What is a test envelope?",
    answer: "A test envelope defines the strict boundaries and parameters of an assessment. It includes the target endpoint, virtual users (VUs), duration, ramp behavior, request mix, and safety caps. Results are always conditional on this envelope."
  },
  {
    id: "q5",
    question: "What are VUs, duration, ramp behavior, and RPS?",
    answer: "VUs (Virtual Users) are concurrent agents executing requests. Duration is the total length of the test. Ramp behavior describes how VUs are introduced over time. RPS (Requests Per Second) measures the throughput of successfully processed requests."
  },
  {
    id: "q5b",
    question: "Where does the test traffic come from?",
    answer: "All test traffic is generated by the ProofScale backend worker (Node.js), never by your browser. You save an ordered sequence of HTTP requests in a test plan, approve it, and the server executes it from the declared target. Your browser only creates plans, starts runs, monitors progress, and views results."
  },
  {
    id: "q5c",
    question: "How are results calculated — are they ever demo or placeholder values?",
    answer: "Every displayed metric (p50/p95/p99 latency, throughput, error rate, threshold pass/fail) is computed from request samples recorded by the worker during your run and evaluated against the plan's configured thresholds. If no run has been recorded yet, the dashboard shows an explicit demo-placeholder label rather than invented numbers."
  },
  {
    id: "q6",
    question: "Can I run assessments against a production environment?",
    answer: "Yes, but production testing requires an approved plan and a separate explicit confirmation step before the run is queued. Targets must be pre-authorized, remote targets must use HTTPS (plain HTTP is limited to local development), and hard caps bound virtual users (50), duration (300s), request rate (100 RPS), and per-request timeout (30s). A global kill switch can halt all execution instantly."
  },
  {
    id: "q7",
    question: "What is the difference between an organization owner, project owner, and tester?",
    answer: "Organization Owners manage members, global guardrails, and projects. Project Owners define targets, construct test plans, and manage project details. Testers can execute approved plans and view reports, but cannot bypass safety settings or modify targets."
  },
  {
    id: "q8",
    question: "How should I interpret p95 latency and throughput?",
    answer: "p95 latency indicates the time within which 95% of your requests completed, highlighting outlier slowdowns. Throughput (RPS) shows the sheer volume of successful requests your application handled. Together, they demonstrate capacity behavior under stress."
  },
  {
    id: "q9",
    question: "Why might two assessments produce different scores?",
    answer: "Scores differ if the test envelope changes—such as altering the workload, request mix, or thresholds—or if the target environment's performance degrades. Valid comparisons require identical test plans and execution parameters."
  },
  {
    id: "q10",
    question: "How does RateCap help keep assessments safe and authorized?",
    answer: "RateCap mandates domain ownership verification, bounded workload caps, role-based access controls, and adherence to predefined test plans. A built-in kill switch and hard safety caps prevent runaway concurrency and protect infrastructure."
  }
];

export function FaqView(props: FaqViewProps) {
  const [openId, setOpenId] = useState<string | null>(null);

  const toggleFaq = (id: string) => {
    setOpenId(openId === id ? null : id);
  };

  return (
    <ThemeProvider>
      <div className="min-h-screen text-[var(--text-1)] relative overflow-x-hidden transition-colors duration-300" style={{ background: "var(--bg-0)" }}>
        <AuroraBackground />
        <HomeNavbar {...props} />

        <main className="relative z-10 max-w-4xl mx-auto px-6 sm:px-12 pt-32 pb-24 space-y-16">
          
          <header className="text-center space-y-4">
            <button
              onClick={props.onGoHome}
              className="mb-8 flex items-center justify-center gap-2 text-sm text-[var(--text-2)] hover:text-[var(--text-1)] transition-colors cursor-pointer mx-auto"
            >
              <ArrowLeft className="w-4 h-4" /> Return to Home
            </button>
            <h1 className="text-4xl md:text-5xl font-black font-display tracking-tight text-[var(--text-1)]">
              Frequently Asked Questions
            </h1>
            <p className="text-lg text-[var(--text-2)] leading-relaxed max-w-2xl mx-auto">
              Clear, technically accurate answers about RateCap’s testing methodology, scoring system, and safety principles.
            </p>
          </header>

          <div className="space-y-4">
            {FAQS.map((faq) => {
              const isOpen = openId === faq.id;
              
              return (
                <div 
                  key={faq.id} 
                  className="glass-panel overflow-hidden transition-all duration-300 rounded-xl"
                >
                  <button
                    onClick={() => toggleFaq(faq.id)}
                    aria-expanded={isOpen}
                    aria-controls={`faq-answer-${faq.id}`}
                    className="w-full text-left px-6 py-5 flex items-center justify-between gap-4 focus:outline-none focus-visible:ring-2 focus-visible:ring-signal-indigo"
                  >
                    <span className="font-bold font-display text-lg text-[var(--text-1)]">
                      {faq.question}
                    </span>
                    <ChevronDown 
                      className={`w-5 h-5 text-signal-indigo transition-transform duration-300 shrink-0 ${isOpen ? "rotate-180" : ""}`} 
                    />
                  </button>
                  
                  <div 
                    id={`faq-answer-${faq.id}`}
                    role="region"
                    aria-hidden={!isOpen}
                    className={`grid transition-all duration-300 ease-in-out ${isOpen ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`}
                  >
                    <div className="overflow-hidden">
                      <div className="px-6 pb-6 pt-2 text-[var(--text-2)] text-sm leading-relaxed border-t border-white/[0.04]">
                        {faq.answer}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="pt-12 border-t border-white/[0.08] flex flex-col items-center justify-center text-center space-y-6">
            <h2 className="text-2xl font-bold font-display text-[var(--text-1)]">Ready to start testing?</h2>
            <p className="text-[var(--text-2)] text-sm">Review the full documentation or jump into your workspace.</p>
            <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
              <button
                onClick={() => props.onNavigate("/docs")}
                className="btn-glass-secondary py-3 px-6 cursor-pointer flex items-center justify-center gap-2"
              >
                Read Documentation
              </button>
              {props.isLoggedIn ? (
                <button
                  onClick={props.onGoToDashboard}
                  className="btn-solid-primary py-3 px-6 cursor-pointer flex items-center justify-center gap-2"
                >
                  Open Workspace <ArrowRight className="w-4 h-4" />
                </button>
              ) : (
                <button
                  onClick={props.onSignUp}
                  className="btn-solid-primary py-3 px-6 cursor-pointer flex items-center justify-center gap-2"
                >
                  Create Account <ArrowRight className="w-4 h-4" />
                </button>
              )}
            </div>
          </div>

        </main>

        <MinimalFooter onSignIn={props.onSignIn} />
      </div>
    </ThemeProvider>
  );
}
